# Generated by Django 4.2.3 on 2023-07-05 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewappUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254, verbose_name='User email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Venue name')),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip code')),
                ('phonenumber', models.CharField(blank=True, max_length=15, verbose_name='Contact phone')),
                ('web', models.URLField(blank=True, verbose_name='website address')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Event name')),
                ('event_date', models.DateTimeField(verbose_name='Event date')),
                ('description', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, to='Events.newappuser')),
                ('manager', models.ForeignKey(blank=True, null=-1, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Events.venue')),
            ],
        ),
    ]
